Add ExceptionlessWindowsEnvironmentInfoCollector
exceptionless/Exceptionless.Net pull request #270
Opened 2022-04-23 03:06 UTC by elachlan

Fixes #269

2022-04-23 03:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/exceptionless/Exceptionless.Net?pullRequest=270) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/exceptionless/Exceptionless.Net?pullRequest=270) before we can accept your contribution.<br/><hr/>**Lachlan Ennis** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/exceptionless/Exceptionless.Net?pullRequest=270) it.</sub>

2022-04-23 06:16 UTC, elachlan commented
I think it might be a good idea to change the config/log fields to be protected so that inherited classes can log warnings and check the config without holding a reference themselves. This would change the API surface though, so I'd thought I'd raise it first.

2022-04-25 23:04 UTC, elachlan commented
If we lazy load `Process`, we need to implement a dispose method as we access `Process.Handle`.
https://stackoverflow.com/questions/16957320/what-does-process-dispose-actually-do

2022-04-26 11:29 UTC, niemyjski requested changes
Thanks for the PR, I will talk to the rest of the team about taking a dependency on win32. We do support this library on .NET 5+ even if it's windows only currently, it may not be some day. Also need to discuss if we feel like it's a good option to create new first-class properties that we would need to support everywhere. I feel like these properties probably should be in a data bag.

2022-04-26 11:29 UTC, niemyjski commented on src/Platforms/Exceptionless.Windows/ExceptionlessWindowsEnvironmentInfoCollector.cs
> +        }
We should make this base class method virtual

2022-04-26 11:50 UTC, elachlan commented
> Thanks for the PR, I will talk to the rest of the team about taking a dependency on win32. We do support this library on .NET 5+ even if it's windows only currently, it may not be some day. Also need to discuss if we feel like it's a good option to create new first-class properties that we would need to support everywhere. I feel like these properties probably should be in a data bag.

I'd like to hope that one-day winforms would run on platforms other than windows. I did ask Microsoft on GitHub about it. But was told winforms will forever be windows only due to its tight coupling with win32.

In WINE calls to these APIs will throw not implemented exceptions I think.

In any case, we can detect the platform and only populate the variables when it's running on windows. Handles are windows specific and so wouldn't make sense to attempt to be populated on Linux.

2022-04-26 15:06 UTC, ejsmith requested changes
Thanks for the contribution @elachlan! Looks good, just a couple changes and we can get this merged.

2022-04-26 15:06 UTC, ejsmith commented on src/Exceptionless/Models/Client/Data/EnvironmentInfo.cs
> +
Definitely agree that this shouldn't be part of this class that is shared across a bunch of platforms. Moving them to data would work.

2022-04-26 15:06 UTC, ejsmith commented on src/Platforms/Exceptionless.Windows/ExceptionlessWindowsEnvironmentInfoCollector.cs
> +        }
Agreed

2022-04-26 22:03 UTC, elachlan commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -        private void PopulateApplicationInfo(EnvironmentInfo info) {
This was dead code.

2022-04-26 22:03 UTC, elachlan commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> +        protected readonly ExceptionlessConfiguration config;
It made sense to expose these to inherited classes as the constructor requires them to begin with.

2022-04-27 23:22 UTC, elachlan commented
> Thanks for the contribution @elachlan! Looks good, just a couple changes and we can get this merged.

Changes are applied, let me know what you both think.

2022-04-28 00:25 UTC, ejsmith requested changes

2022-04-28 00:25 UTC, ejsmith commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> +        protected readonly ExceptionlessConfiguration config;
These should still be prefixed with an `_` as that is our naming convention.

2022-04-28 00:25 UTC, ejsmith commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -            _config = config;
These should be reverted to use `_`

2022-04-28 00:59 UTC, elachlan commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -            _config = config;
No problem. Visual Studio was complaining at me that `_` should only be used when something is private.

2022-04-28 00:59 UTC, elachlan commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -            _config = config;
https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs3008?f1url=%3FappId%3Droslyn%26k%3Dk(CS3008)

2022-04-28 01:02 UTC, elachlan commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -            _config = config;
I'll switch it to private and expose a property to access them.

2022-04-28 01:04 UTC, ejsmith commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -            _config = config;
I'm not saying they should be private. They can be protected.

2022-04-28 01:06 UTC, elachlan commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -            _config = config;
Renaming them to underscore causes CS3008 warning. so its best to have them private with underscore and expose them via a protected property.

Like this:
```
private readonly ExceptionlessConfiguration _config;
private readonly IExceptionlessLog _log;
protected ExceptionlessConfiguration Config => _config;
protected IExceptionlessLog Log => _log;
```

2022-04-28 01:22 UTC, ejsmith commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -            _config = config;
Hmm... I guess the `CLSCompliant` attribute is doing it. They do recommend turning them into protected properties. I guess just make them protected auto properties without a backing field.

2022-04-28 01:27 UTC, elachlan commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -            _config = config;
So its okay without the leading underscore?

2022-04-28 01:32 UTC, ejsmith commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -            _config = config;
No, was thinking like this:

```csharp
        public DefaultEnvironmentInfoCollector(ExceptionlessConfiguration config, IExceptionlessLog log) {
            Config = config;
            Log = log;
        }

        protected ExceptionlessConfiguration Config { get; }
        protected IExceptionlessLog Log { get; }
```

2022-04-28 01:42 UTC, elachlan commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -            _config = config;
How is that?

2022-04-28 03:05 UTC, ejsmith submitted a review, later dismissed
LGTM thank you @elachlan

2022-04-28 03:14 UTC, elachlan commented
The only nitpick I have is that GetGuiResources has the ability to query the peak count on GDI and User objects. Which might be helpful. But as per the documentation for it, it isn't supported on older windows versions:
`Windows Server 2008, Windows Vista, Windows Server 2003 and Windows XP:  This value is not supported until Windows 7 and Windows Server 2008 R2.`

That being said, I don't think that matters because of the requirement for .NET 4.6.2 by this package. Which is Win 7 Minimum.

2022-04-28 11:02 UTC, niemyjski commented on src/Platforms/Exceptionless.Windows/ExceptionlessWindowsExtensions.cs
> +            client.Configuration.Resolver.Register<IEnvironmentInfoCollector, ExceptionlessWindowsEnvironmentInfoCollector>();
Can we confirm if that the WPF extensions method doesn't call this.

2022-04-28 11:02 UTC, niemyjski commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -        private void PopulateApplicationInfo(EnvironmentInfo info) {
Can we see when this was removed (and link to commit) and hook it back up. Looking at this, we should be capturing this data.

2022-04-28 11:41 UTC, elachlan commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -        private void PopulateApplicationInfo(EnvironmentInfo info) {
It was added in Jun-2016: https://github.com/exceptionless/Exceptionless.Net/commit/3fa990d553b2e01621899a4c1b18833b807ead7b

For whatever reason, it was added and never used. Similar information is pulled in as apart of `PopulateProcessInfo()`.

2022-04-28 11:44 UTC, niemyjski commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -        private void PopulateApplicationInfo(EnvironmentInfo info) {
That's weird, can we hook them back up.

2022-04-28 11:49 UTC, elachlan commented on src/Platforms/Exceptionless.Windows/ExceptionlessWindowsExtensions.cs
> +            client.Configuration.Resolver.Register<IEnvironmentInfoCollector, ExceptionlessWindowsEnvironmentInfoCollector>();
Exceptionless.WPF and Exceptionless.Windows are separate projects and don't have any dependencies on each other as far as I can tell.

2022-04-28 11:54 UTC, elachlan commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -        private void PopulateApplicationInfo(EnvironmentInfo info) {
`PopulateApplicationInfo()` uses `AppDomain.CurrentDomain.FriendlyName`. This is almost effectively the same as `process.ProcessName` populating the processname in `PopulateProcessInfo()`. 

Additionally, I think the IP Address is populated server side. Do you think that might clash when we add a local IP Address?

2022-04-28 12:00 UTC, elachlan commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -        private void PopulateApplicationInfo(EnvironmentInfo info) {
Based on these, I am fairly certain they have the same information.
https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.friendlyname?view=net-6.0
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.processname?view=net-6.0

2022-04-28 21:58 UTC, elachlan commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -        private void PopulateApplicationInfo(EnvironmentInfo info) {
@niemyjski do you think it is still needed based on that information?

2022-04-28 22:00 UTC, elachlan commented on src/Platforms/Exceptionless.Windows/ExceptionlessWindowsExtensions.cs
> +            client.Configuration.Resolver.Register<IEnvironmentInfoCollector, ExceptionlessWindowsEnvironmentInfoCollector>();
@niemyjski are you satisfied based on the information provided above?

2022-04-30 20:09 UTC, niemyjski commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -        private void PopulateApplicationInfo(EnvironmentInfo info) {
Let's revert this change and wire it up.

2022-05-02 03:24 UTC, elachlan commented on src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs
> -        private void PopulateApplicationInfo(EnvironmentInfo info) {
Done!

2022-05-02 11:15 UTC, niemyjski approved these changes

2022-05-02 11:16 UTC, merged

2022-05-02 11:16 UTC, niemyjski commented
Thanks for the PR!

2022-05-02 21:25 UTC, elachlan commented
@niemyjski thank you for the review! Are you able to do a release sometime soon?

2022-05-03 01:08 UTC, niemyjski commented
We typically like to let a nightly sit for a little bit (week or two), we have a nightly NuGet feed you can use.